language: node_js

node_js:
   - 8
   - 9

env:
  global:
    - INT_COUCHDB_URL="http://localhost:5984/medic-analytics-test"

sudo: false

services:
   - couchdb

addons:
   postgresql: "9.4"

script:
   - yarn ci

# notifications:
#   webhooks:
#     urls:
#       - https://medic.slack.com/services/hooks/travis?token=xcYT8yusfEdSwLskhBxK4Vwj
#     on_success: change
#     on_failure: always
#   email:
#     recipients:
#       - dev@medicmobile.org
